CREATE TABLE t_setting(
id int not null generated by default as identity,
name varchar(100) not null,
line varchar(20),
train varchar(20),
last_modify timestamp,
raw_strategy int,
result_strategy int,
raw_space int,
result_space int,
time_on boolean,
selected boolean,
retry_ip varchar(20),
PRIMARY KEY(id)
);

CREATE TABLE t_board_setting(
id int not null generated by default as identity,
setting_id int not null,
enable boolean,
ip varchar(20),
slot_id int,
type varchar(50),
filename varchar(255),
file_original_name varchar(255),
PRIMARY KEY(id)
);

CREATE TABLE t_algorithm_setting(
id int not null generated by default as identity,
setting_id int not null,
name varchar(100) not null,
code int,
slot_id int,
type int,
enable boolean,
filename varchar(255),
file_original_name varchar(255),
subsystem_id int,
PRIMARY KEY(id)
);

CREATE TABLE t_subsystem(
id int not null generated by default as identity,
name varchar(50) not null,
description varchar(200),
PRIMARY KEY(id)
);

CREATE TABLE t_variable_group(
id int not null generated by default as identity,
type varchar(10),
consumption_id bigint,
multicast_ip varchar(20),
multicast_port int,
PRIMARY KEY(id)
);

CREATE TABLE t_time_setting(
setting_id int not null,
group_id int,
PRIMARY KEY(setting_id)
);

CREATE TABLE t_storage_variable(
setting_id int not null,
group_id int,
PRIMARY KEY(setting_id,group_id)
);

CREATE TABLE t_board_variable(
board_id int not null,
group_id int not null,
PRIMARY KEY(board_id,group_id)
);

CREATE TABLE t_algorithm_variable(
algorithm_id int not null,
group_id int not null,
PRIMARY KEY(algorithm_id,group_id)
);

CREATE TABLE t_ad_variable(
id bigint not null generated by default as identity,
group_id int not null,
chn_id int,
sample_rate double,
clock_src double,
frequence_factor double,
signal_name varchar(100),
PRIMARY KEY(id)
);

CREATE TABLE t_mvb_variable(
id bigint not null generated by default as identity,
group_id int,
device int,
device_name varchar(100),
carriage varchar(100),
system varchar(100),
port int,
fcode int,
data_type int,
byte_offset int,
bit_offset int,
bit_len int,
name varchar(100),
unit varchar(100),
signal_name varchar(200),
PRIMARY KEY(id)
);

CREATE TABLE t_ecn_variable(
id bigint not null generated by default as identity,
group_id int,
source_ip varchar(20),
com_id bigint,
data_type int,
byte_offset int,
bit_offset int,
bit_len int,
name varchar(100),
unit varchar(100),
signal_name varchar(200),
PRIMARY KEY(id)
);


