server:
  port: 18081
  tomcat:
    uri-encoding: utf-8
    max-threads: 2000
    max-connections: 20000
spring:
  datasource:
    druid:
      # 数据库访问配置, 使用druid数据源 
      db-type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/axle_temp_phm_db?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: 123456

#  aop:
#    proxy-target-class: true
  cache:    type: redis
  servlet:    multipart:      max-file-size: -1
      max-request-size: -1        
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis 密码
    password:
    jedis:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
    # 连接超时时间（毫秒）
    timeout: 0          
#logging: 
#  level:  
#    #(TRACE, DEBUG, INFO, WARN,ERROR, FATAL, OFF)
#    com.hirain.qsy.shaft.dao: DEBUG


mybatis:
  # mapper xml实现扫描路径
  mapper-locations: classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: null
    map-underscore-to-camel-case: true
    

