INSERT INTO ROOT.T_USER (ID,USERNAME,PASSWORD) VALUES (
1,'admin','admin');

INSERT INTO ROOT.T_ROLE (ID,ROLENAME,CNAME) VALUES (
1,'admin','管理员');
INSERT INTO ROOT.T_ROLE (ID,ROLENAME,CNAME) VALUES (
2,'common','普通用户');


INSERT INTO ROOT.T_USER_ROLE
(USER_ID, ROLE_ID)
VALUES(1, 1);

INSERT INTO ROOT.T_SETTING
(ID, NAME, SELECTED)
VALUES(1, '默认配置', true);

